const mapping = {
  adb: 'gnatmake',
  asm: (x) => `as ${x}.s -o ${x}.o;ld ${x}.o -o ${x}`,
  awk: 'awk -f',
  c: (x) => `gcc -o ${x} ${x}.c`,
  clj: 'clojure',
  cob: (x) => `cobc -x -W -free ${x}.cob`,
  cpp: (x) => `g++ -o ${x} ${x}.cpp`,
  cr: 'crystal build',
  cs: 'mcs',
  d: 'dmd',
  dart: 'dart',
  erl: 'erlc',
  ex: 'elixirc',
  f95: (x) => `gfortran -o ${x} ${x}.f95`,
  fs: 'fsharpc',
  go: 'go run', // go: 'go build',
  groovy: 'groovyc',
  hs: (x) => `ghc -o ${x} ${x}.hs`,
  java: 'javac',
  jl: 'julia', 
  js: 'node',
  kt: (x) => `kotlinc ${x}.kt -include-runtime -d ${x}`,
  lisp: (x) => `sbcl --non-interactive --eval '(compile-file "${x}.lisp")'`,
  lua: 'lua', // lua: (x) => `luac -o ${x} ${x}.lua`,
  m: 'octave',
  ml: (x) => `ocamlc -o ${x} ${x}.ml`,
  nim: 'nim c -r',
  pas: 'fpc',
  php: 'php',
  pl: 'perl',
  py: 'python',
  r: 'Rscript',
  rb: 'ruby',
  rkt: 'racket',
  rs: 'rustc',
  scala: (x) => `${x}.scala -d ${x}.jar`,
  sml: 'mlton',
  st: 'gst',
  swift: 'swiftc',
  ts: 'ts-node',
  vb: 'vbnc',
  wat: (x) => `wat2wasm -o ${x}.wasm ${x}.wat`,
};

export default mapping;
